app/Organizer/urls.py
from .views import *
from django.conf import settings
from django.conf.urls import url, include
from django.urls import include, path
from django.urls import path

"""
Urls de Organizer
"""
urlpatterns = [
    path('eventos/Invitacion/<int:evento_id>/all', Invitaciones,
         name='Invitaciones'),
    path('eventos/Invitacion/new', nuevaInvitacion, name='nuevaInvitacion'),
    path('eventos/delete/<int:id>/',deleteEvent,name='deleteEvent'),
    path('eventos/misEventos', listMyEvents,name='listMyEvents'),
    path('eventos/new', createEvent, name='createEvent'),
    path('eventos/see/<int:id>/',seeEvent,name='seeEvent'),
    path('eventos/update/<int:id>/',updateEvent,name='updateEvent'),
    ######## STAFF ########
    path('MisStaffs/delete/<int:id>/',deleteStaff,name='deleteStaff'),
    path('MisStaffs/listStaffs', listStaffs, name='listStaffs'),
    path('MisStaffs/new', addStaff, name='addStaff'),
    ######## EVENTS SEARCH ########
    path('search/', SearchEventsView.as_view(), name='search_results'),
    ######## REGISTER EVENT ########
    path('eventos/register/<str:id1>/<str:id2>', RegisterEvent,
         name='registerEvent'),
    ######## CREATE TAG ########
    path('tags', newTag, name='newTag'),
]

app/User/urls.py
from . import views
from .views import *
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.urls import path

"""
Todas las urls en User
"""

app_name = 'User'
urlpatterns = [
    #path('accounts/', include('django.contrib.auth.urls')),
    #;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    #TODAS LAS SIGUIENTES DIRECCIONES VIENEN CON LA DE ARRIBA
    #accounts/login/ [name='login']
    #accounts/logout/ [name='logout']
    #accounts/password_change/ [name='password_change']
    #accounts/password_change/done/ [name='password_change_done']
    #accounts/password_reset/ [name='password_reset']
    #accounts/password_reset/done/ [name='password_reset_done']
    #accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    #accounts/reset/done/ [name='password_reset_complete']
    #;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    path("error505",error505, name="error505"),
    path('',Index, name='index'),
    path('about/', views.About.as_view(), name='about'),
    path('admin/', admin.site.urls),
    path('eventos/',views.EventosN.as_view(), name='eventos'),
    path('eventos/all',EventosList, name='eventosList'),
    path('eventos/home',Eventos, name='eventosHome'),
    path('eventos/home.html',Eventos, name='eventosHome'),
    path('eventos/index.html/',Eventos, name='eventos'),
    path('eventos/index/',Eventos, name='eventos'),
    path('home/', views.HomeView.as_view(),name='home'),
    path('home/',Index, name='index'),
    path('login/', views.SignInView.as_view(), name='login'),
    path('login/register.html/', views.Register, name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.SignUpView.as_view(), name='register2'),
    path('register/Organizador/', views.RegistroOrganizador.as_view(),
         name='registroOrg'),
    path('register/cambioContrasena/', views.CambioContrasena.as_view(),
         name='cambio'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^organizador_registrado/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.organizador_registrado, name='organizador_registrado'),
    url(r'^register/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activateEvent, name='activateEvent'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls')),
    path('', include('Organizer.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/Organizer/models.py
from User.models import User
from django.contrib.auth.models import User as UserDjango
from django.db import models
from django import forms
from django.template.defaultfilters import slugify
import django

# Create your models here.

class Etiqueta(models.Model):
    """
    Modelo de etiqueta
    """
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return str(self.nombre)

class Evento(models.Model):
    """
    Modelo del evento
    """
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    direccion = models.TextField()
    horario_inicio = models.TimeField()
    horario_fin = models.TimeField()
    capacidad = models.IntegerField()
    etiqueta = models.ManyToManyField(Etiqueta)
    organizador = models.ForeignKey(User, on_delete=models.CASCADE)
    #periodicidad =

    def __str__(self):
        return str(self.nombre) + ': ' + str(self.fecha_inicio)

class Invitacion(models.Model):
    """
    Modelo de la invitación
    """
    evento_id = models.ForeignKey(Evento, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    activa = models.BooleanField() # True si aún no se lee en el evento
    asistencia_activa = models.BooleanField() # True si ya se leyó en el evento
    qr = models.ImageField(upload_to='images/', blank=True, null=True)

    class Meta:
        """
        Llave compuesta
        """
        unique_together = (('evento_id', 'user_id'),)

    def __str__(self):
        return str(self.evento_id) + '--' + str(self.user_id)

class Staff(models.Model):
    """
    Modelo del Staff
    """
    user_id = models.ForeignKey(User,on_delete=models.CASCADE, related_name="staffs")
    evento_id = models.ForeignKey(Evento,on_delete=models.CASCADE)

class ValidaInvitacion(models.Model):
    """
    Modelo para validar una invitación
    """
    user_id = models.ForeignKey(Staff,on_delete=models.CASCADE)
    invitacion_id = models.ForeignKey(Invitacion,on_delete=models.CASCADE)
    class Meta:
        """
        Llave compuesta
        """
        unique_together = (('user_id', 'invitacion_id'),)

app/Organizer/forms.py
from .models import Evento,Staff,Invitacion, Etiqueta
from django import forms

class EventosForm(forms.ModelForm):
    """
    Datos que pedimos para registrar un evento
    """
    class Meta:
	    model= Evento
	    fields= ['nombre','descripcion','fecha_inicio', 'fecha_fin', 
		     'direccion', 'horario_inicio', 'horario_fin', 'capacidad', 
		     'etiqueta','organizador']
		
class StaffForm(forms.ModelForm):
    """
    Datos para el staff.
    """
    class Meta:
	    model = Staff
	    fields = ['user_id','evento_id']

class InvitacionesForm(forms.ModelForm):
    """
    Datos que se piden para mandar una invitación.
    """
    class Meta(object):
	    model = Invitacion
	    fields = ['evento_id','user_id','activa','asistencia_activa', 'qr',]

class EtiquetaForm(forms.ModelForm):
    """
    Datos para la etiqueta
    """
    class Meta:
	    model = Etiqueta
	    fields = ['nombre']

app/Organizer/views.py
from .forms import EventosForm, StaffForm, InvitacionesForm, EtiquetaForm
from .models import Evento, Staff, Invitacion, Etiqueta
from .utils import send_email, invitacion_activacion_token, make_qr
from PIL import Image
from User.models import User, Usuario
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMultiAlternatives, EmailMessage
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.template.loader import get_template
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import TemplateView, ListView
import qrcode

def nuevaInvitacion(request):
    """
    Generar nueva invitación
    """
    form = InvitacionesForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('Invitaciones')
    return render(request,'invitacionesForm.html',{'form':form})

def Invitaciones(request,evento_id):
    """
    Vista de las invitaciones
    """
    evento = Evento.objects.all()
    invitaciones= Invitacion.objects.all()
    return render(request,'invitaciones.html',{'invitaciones':invitaciones})

def RegisterEvent(request, id1, id2):
    """
    Vista para registrar un evento
    """
    evento = Evento.objects.get(pk=id1)
    # usuario = User.objects.get(pk=id2)
    usuario = request.user
    template = 'registerEvent.html'
    context = {'evento':evento, 'user':usuario}
    if request.method == 'POST':
        current_site = get_current_site(request)
        subject = 'Invitación a ' + evento.nombre
        content = 'Tienes una cita el día: ' + str(evento.fecha_inicio) + ' para el evento: ' + evento.nombre
        guest = [usuario.email]
        inv_count = Invitacion.objects.filter(evento_id=id1).count()
        print('COUNT>>', inv_count)
        inv = Invitacion(evento_id=evento, user_id=usuario, activa=True,
                         asistencia_activa=False)
        inv.save()
        if inv_count > evento.capacidad:
            return HttpResponse('Ya no hay lugares disponibles :(')
        message = render_to_string('registration_mail.html', {
            'user': usuario,
            'domain': current_site.domain,
            'uid':urlsafe_base64_encode(force_bytes(inv.pk)),
            'token':invitacion_activacion_token.make_token(inv), # esto me causa dudas
        })
        img = make_qr(message)
        img.save('images/' + str(id1) + str(request.user) + '.png')
        nombre = 'images/' + str(id1) + str(request.user) + '.png'
        im = Image.open(nombre)
        Invitacion.objects.filter(pk=id1).update(qr=im)
        content += message
        # Generar el correo en html
        email = EmailMessage(subject, content, settings.EMAIL_HOST_USER, guest)
        email.attach_file('images/' + str(id1) + str(request.user) + '.png')
        email.send()
        print(usuario.email)
        print(evento.nombre)
        return render(request, 'invitacionEnviada.html')    
    return render(request, template, context)                

##########################################################################
#Events Stuff
##########################################################################

def listMyEvents(request):
    """
    Vista de listar eventos 
    """
    eventos=Evento.objects.all()
    return render(request,'myEvents.html',{'eventos':eventos})

def seeEvent(request,id):
    """
    Vista para ver un evento en específico
    """
    evento = Evento.objects.get(id=id)
    return render(request,'verEvento.html',{'evento':evento})

def createEvent(request):
    """
    Vista para crear un evento
    """
    form = EventosForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('listMyEvents')
    return render(request,'eventsForm.html',{'form':form})

def updateEvent(request, id):
    """
    Vista para actualizar un evento
    """
    evento = Evento.objects.get(id=id)
    form = EventosForm(request.POST or None, instance=evento)
    if form.is_valid():
        form.save()
        return redirect('listMyEvents')
    return render(request,'eventsForm.html',{'form':form, 'evento':evento})
# EventosForm no sirve (?)

def deleteEvent(request, id):
    """
    Vista para borrar un evento
    """
    evento = Evento.objects.get(id=id)
    if request.method == 'POST':
        print(evento)
        evento.delete()
        return redirect('listMyEvents')
    return render(request, 'prod_delete-confirm.html',{'evento':evento})

class SearchEventsView(ListView):
    """
    Vista para buscar eventos
    """
    model = Evento
    template_name = 'search_results.html'
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Evento.objects.filter(
            # Lista de cosas por las que se puede buscar un evento
            Q(nombre__icontains=query) |
            Q(descripcion__icontains=query) |
            Q(direccion__icontains=query) |
            Q(fecha_inicio__icontains=query) | 
            Q(etiqueta__nombre__icontains=query)
        )
        return object_list

##########################################################################
#Staff Stuff
##########################################################################

def addStaff(request):
    """
    Agregar un staff
    """
    form = StaffForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('listStaffs')
    return render(request,'staffForm.html',{'form':form})

def deleteStaff(request, id):
    """
    Borrar un staff
    """
    staff = Staff.objects.get(id=id)
    if request.method == 'POST':
        staff.delete()
        return redirect('listMyEvents')
    return render(request, 'prod_delete-confirm.html',{'staff':staff})

def listStaffs(request):
    """
    Listar a todos los staffs
    """
    eventos=Evento.objects.all()
    staffs=Staff.objects.all()
    return render(request,'myStaffs.html',{'eventos':eventos, 'staffs':staffs})

##########################################################################
# CREATE TAG
##########################################################################

def newTag(request):
    """
    Agregar un TAG
    """
    tags=Etiqueta.objects.all()
    form = EtiquetaForm(request.POST or None)
    if form.is_valid():
        form.save()
        print('ulmo')
        return redirect('createEvent')
    print('ulmo2')
    return render(request,'createTag.html',{'etiquetas':tags})

app/Organizer/templates/buscarEventos.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Eventos</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../../static/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../../static/vendors/iconfonts/puse-icons-feather/feather.css">
    <link rel="stylesheet" href="../../../static/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../../static/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="../../../static/css/shared/style.css">
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../../static/css/demo_1/style.css">
    <link rel="stylesheet" href="../../../static/css/demo_3/dark-theme.css">
    <!-- End Layout styles -->
    <link rel="shortcut icon" href="../../../static/images/favicon.png" /> </head>
  <body class="dark-theme sidebar-dark">
    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      {% include 'partials/_navbar.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_settings-panel.html -->
          {% include 'partials/_settings-panel.html' %}
        <!-- partial -->
        <!-- partial:partials/_sidebar.html -->
          {% include 'partials/_sidebar.html' %}   
        <!-- partial -->

        <!-- AQUI va el codigo base!! -->
        <head>
            <title>Buscar Eventos{% if query %} Resultados{%endif%}</title>
        </head>
        <body>
            <h1>Buscar</h1>
            <form action="." method="GET">
                <label for="q">Search: </label>
                <input type="text" name="q" value="{{ query|escape }}">
                <input type="submit" value="Search">
            </form>

            {% if query %}
                <h2>Results for "{{ query|escape }}":</h2>
            {% if results %}
                <ul>
                {% for evento in resultado %}
                    <li>{{ evento|escape }}</l1>
                {% endfor %}
                </ul>
                {% else %}
                    <p>No se encontraron eventos</p>
                {% endif %}
                {% endif %}
        </body>
        <!-- AQUI Termina el codigo base!! -->


          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
            {% include 'partials/_footer.html' %}
          <!-- partial -->
        <!-- main-panel ends -->
        </div>
      <!-- page-body-wrapper ends -->
      </div>
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="../../../../static/vendors/js/vendor.bundle.base.js"></script>
    <script src="../../../static/vendors/js/vendor.bundle.addons.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="../../../static/js/shared/off-canvas.js"></script>
    <script src="../../../static/js/shared/hoverable-collapse.js"></script>
    <script src="../../../static/js/shared/misc.js"></script>
    <script src="../../../static/js/shared/settings.js"></script>
    <script src="../../../static/js/shared/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <!-- End custom js for this page-->
  </body>
</html>

app/Organizer/templates/createTag.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Eventos</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../../static/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../../static/vendors/iconfonts/puse-icons-feather/feather.css">
    <link rel="stylesheet" href="../../../static/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../../static/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="../../../static/css/shared/style.css">
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../../static/css/demo_1/style.css">
    <link rel="stylesheet" href="../../../static/css/demo_3/dark-theme.css">
    <!-- End Layout styles -->
    <link rel="shortcut icon" href="../../../static/images/favicon.png" /> </head>
  <body class="dark-theme sidebar-dark">
    <div class="container-scroller">
      <!-- partial:../../partials/_navbar.html -->
      {% include 'partials/_navbar.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:../../partials/_settings-panel.html -->
        {% include 'partials/_settings-panel.html' %}
        <!-- partial -->
        <!-- partial:../../partials/_sidebar.html -->
        {% include 'partials/_sidebar.html' %}
        <!-- partial -->

        <!-- AQUI va el codigo base!! -->

        <div class="main-panel">
          <div class="content-wrapper">
            <div class="card">
              <div class="card-body">

            <h1>Crea una etiqueta.</h1>
            <form method="POST">
              {% csrf_token %}
              {{ form.non_field_errors }}
              <div class="card-body">
                <div>
                  <h3>Información General</h3>
                  <section>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="nombre">Nombre:</label>
                      <input type="text" class="form-control" name="nombre" placeholder="nombre">
                    </div>
                  </section>

                </div>

                <button type="submit">Save</button>
            </form>


            <!-- AQUI Termina el codigo base!! -->


            </div>
            </div>
            </div>
            <!-- content-wrapper ends -->
            <!-- partial:../../partials/_footer.html -->
            {% include 'partials/_footer.html' %}
            <!-- partial -->
            <!-- main-panel ends -->
          </div>
          <!-- page-body-wrapper ends -->
        </div>
      </div>
      <!-- container-scroller -->
      <!-- plugins:js -->
      <script src="../../../../static/vendors/js/vendor.bundle.base.js"></script>
      <script src="../../../static/vendors/js/vendor.bundle.addons.js"></script>
      <!-- endinject -->
      <!-- Plugin js for this page-->
      <!-- End plugin js for this page-->
      <!-- inject:js -->
      <script src="../../../static/js/shared/off-canvas.js"></script>
      <script src="../../../static/js/shared/hoverable-collapse.js"></script>
      <script src="../../../static/js/shared/misc.js"></script>
      <script src="../../../static/js/shared/settings.js"></script>
      <script src="../../../static/js/shared/todolist.js"></script>
      <!-- endinject -->
      <script src="../../../assets/js/shared/wizard.js"></script>
      <!-- Custom js for this page-->
      <!-- End custom js for this page-->
  </body>
</html>

app/Organizer/templates/eventsForm.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Eventos</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../../static/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../../static/vendors/iconfonts/puse-icons-feather/feather.css">
    <link rel="stylesheet" href="../../../static/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../../static/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="../../../static/css/shared/style.css">
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../../static/css/demo_1/style.css">
    <link rel="stylesheet" href="../../../static/css/demo_3/dark-theme.css">
    <!-- End Layout styles -->
    <link rel="shortcut icon" href="../../../static/images/favicon.png" /> </head>
  <body class="dark-theme sidebar-dark">
    <div class="container-scroller">
      <!-- partial:../../partials/_navbar.html -->
      {% include 'partials/_navbar.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:../../partials/_settings-panel.html -->
        {% include 'partials/_settings-panel.html' %}
        <!-- partial -->
        <!-- partial:../../partials/_sidebar.html -->
        {% include 'partials/_sidebar.html' %}
        <!-- partial -->

        <!-- AQUI va el codigo base!! -->
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="card">
              <div class="card-body">

            <h1>New/Update Event</h1>
            <form method="POST">
              {% csrf_token %}
              {{ form.non_field_errors }}
              <div class="card-body">
                <div>
                  <h3>Información General</h3>
                  <section>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="userName">Nombre:</label>
                      <input type="text" class="form-control" name="nombre" placeholder="nombre">
                    </div>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="ev_nombre">Descripción:</label>
                      <input type="text" class="form-control" name="descripcion" placeholder="Escribe una descripcion">
                    </div>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="ev_nombre">Dirección:</label>
                      <input type="text" class="form-control" name="direccion" placeholder="Escribe una direccion">
                    </div>
                  </section>
                  <hr>
                  <h3>Horarios y Fechas</h3>
                  <section>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="ev_nombre">Fecha de inicio:</label>
                      <input type="text" class="form-control" name="fecha_inicio" placeholder="Escribe una fecha dd/mm/aaaa">
                    </div>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="ev_nombre">Fecha de finalización:</label>
                      <input type="text" class="form-control" name="fecha_fin" placeholder="Escribe una fecha dd/mm/aaaa">
                    </div>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="ev_nombre">Hora de inicio:</label>
                      <input type="text" class="form-control" name="horario_inicio" placeholder="Escribe una hora hh:mm">
                    </div>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="ev_nombre">Hora de termino:</label>
                      <input type="text" class="form-control" name="horario_fin" placeholder="Escribe una hora hh:mm">
                    </div>
                  </section>
                  <hr>
                  <h3>Otros</h3>
                  <section>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="ev_nombre">Capacidad:</label>
                      {{ form.capacidad }}
                    </div>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      <label for="ev_nombre">Selecciona una etiqueta:</label>
                      {{ form.etiqueta }}
                      <h5>¿No está la etiqueta que buscas?</h5>
                      <a href="/../tags">Crea una</a>
                    </div>
                    <div class="fieldWrapper">
                      {{ form.subject.errors}}
                      {{ form.organizador.as_hidden }}
                    </div>
                  </section>
                </div>

                <button type="submit">Save</button>
            </form>
            {% if evento %}
            <a href="{% url 'deleteEvent' evento.id %}">Delete</a>
            {% endif %}


            <!-- AQUI Termina el codigo base!! -->


            </div>
            </div>
            </div>
            <!-- content-wrapper ends -->
            <!-- partial:../../partials/_footer.html -->
            {% include 'partials/_footer.html' %}
            <!-- partial -->
            <!-- main-panel ends -->
          </div>
          <!-- page-body-wrapper ends -->
        </div>
      </div>
      <!-- container-scroller -->
      <!-- plugins:js -->
      <script src="../../../../static/vendors/js/vendor.bundle.base.js"></script>
      <script src="../../../static/vendors/js/vendor.bundle.addons.js"></script>
      <!-- endinject -->
      <!-- Plugin js for this page-->
      <!-- End plugin js for this page-->
      <!-- inject:js -->
      <script src="../../../static/js/shared/off-canvas.js"></script>
      <script src="../../../static/js/shared/hoverable-collapse.js"></script>
      <script src="../../../static/js/shared/misc.js"></script>
      <script src="../../../static/js/shared/settings.js"></script>
      <script src="../../../static/js/shared/todolist.js"></script>
      <!-- endinject -->
      <script src="../../../assets/js/shared/wizard.js"></script>
      <!-- Custom js for this page-->
      <!-- End custom js for this page-->
  </body>
</html>

app/Organizer/templates/mail.html
<h1>Hola {{user.username}} </h1>,
<h2>Por favor enseña la siguiente dirección a un miembro del staff para registrar tu entrada:</h2>
<div class="profile-image">
  <img src="12.png.url">
</div>

app/Organizer/templates/registration_mail.html
{% autoescape off %}
http://{{ domain }}{% url 'User:activateEvent' uidb64=uid token=token %}
{% endautoescape %}